### ISSUE TITLE
Feedback on table 2 in section 2.3.2: Required Window Size for 100-ms RTT

### ISSUE THREAD

**Issue by byllyfish** [SystemsApproach/tcpcc#14]
I'm wondering about the use of the term "RTT" (ie round-trip-time).  When talking about `AdvertisedWindow`, isn't the delay just the trip time in one direction?

Also, I re-did the calculations for this table and I get slightly different numbers for the last three rows of table 2:

For 2.5 Gbps, I get 29.8 MB (the text says 29.6)

For 10 Gbps, I get 119.2 MB (the text says 118.4 MB).

My formula is `=BPS/8*0.1/(1024*1024)` where `BPS` assumes Gbps indicates power of 10 and MB is 2^20.

FWIW, for both tables 1 and 2, I think numbers to a precision of .1 might be more useful... I've included my spreadsheet below.

BPS | KB | MB | TTW (secs) | Time To Wrap |  
-- | -- | -- | -- | -- | --
1.50E+06 | 18.3 |   | 22,906.49 | 6.4 | hours
4.50E+07 | 549.3 |   | 763.55 | 12.7 | minutes
1.55E+08 |   | 1.8 | 221.68 | 3.7 | minutes
2.50E+09 |   | 29.8 | 13.74 | 13.7 | seconds
1.00E+10 |   | 119.2 | 3.44 | 3.4 | seconds

**Comment by drbruced12** [comment]
RTT (round trip) is correct because the time from when you send the first byte of a window, until the time that byte is acknowledged, is one full RTT (the ack has to come back). Hence, you need a full RTT of data in flight to keep the pipe full, and this is what the advertised window is trying to allow.

As for the differences in our numbers, it actually comes from our being a bit sloppy in describing the bandwidth of OC-48 and OC-192, which are 2.48 and 9.6 Gbps. (Our 10Gbps Ethernet number should match your number - looks like we copied it from the OC-192 number.) Although even these numbers are approximate due to SONET overhead. 

Agreed that we should be consistent on one decimal place precision. 

I think there is an opportunity for us to improve this, which I will attend to shortly. Thanks for the feedback.

**Comment by llpeterson** [comment]
Changes have been merged.
