### ISSUE TITLE
2.3.1 Protecting Against Wraparound - Table 1 has incorrect values for first row with bandwidth = 1.5Mbps

### ISSUE THREAD

**Issue by goelvidhi** [SystemsApproach/tcpcc#35]
Correct value is 6.4 hours with 1 Mbps = 1000 * 1000 bps

**Comment by drbruced12** [comment]
The real issue here is that T1 is actually 1.544 Mbps, and so if you do the calculation for T1, you get 6.2 hours. And the main point to the table is to illustrate orders of magnitude, which is why we don't show 4 significant figures for everything. Interestingly, we previously had similar issues around the accuracy of figures for OC-48 and OC-192 due to both rounding errors and the SONET overhead (the bandwidth actually available for TCP/IP is less than 2.5 and 10 Gbps)
