### ISSUE TITLE
Table 2 in 2.3.2 has incorrect BDP values

### ISSUE THREAD

**Issue by goelvidhi** [SystemsApproach/tcpcc#36]
Correct values are below with 1KB = 1024 bytes
<img width="438" alt="Screen Shot 2022-06-21 at 11 58 02 AM" src="https://user-images.githubusercontent.com/10913828/174877196-1d12b6d3-ca04-4e76-9b9e-f1224dd65cef.png">

**Comment by drbruced12** [comment]
I believe the differences here are due to rounding issues with the stated line rates. For example, T1 is actually 1.544 with leads to the 18.8 result. We decided to only show one decimal place but (based on feedback from another reader) we did all the calculations using the actual bandwidths (to 4 significant figures) of the circuit types in question. OC-192, for example, has a payload bandwidth of 9.511 Gbps which explains the difference. Given that we're only trying to show orders of magnitude here, it doesn't seem worth a lengthy discussion about precision (however we do cover that in chapter 1 of Computer Networks). Nevertheless, obviously some people get bothered by this as you're not the first person to suggest we re-check our numbers. Perhaps we should add a footnote.
