### ISSUE TITLE
4 Control-Based algorithms

### ISSUE THREAD

**Issue by goelvidhi** [SystemsApproach/tcpcc#37]
Suggestions for the below text,

Current text,
```"...a TCP sender reacts to two signals from the network. On the one hand, the arrival of an ACK signals that one of its packets has left the network and that it is therefore safe to transmit a new packet without adding to the level of congestion. By using ACKs to pace the transmission of packets, TCP is said to be self-clocking. On the other hand, a timeout signals that a packet was lost, implying that the network is congested, and thus TCP needs to reduce its sending rate."```

Suggestion,
```"... a sender reacts to implicit or explicit signals from the network. The arrival of an ACK signals that one of its packets has left the network and a sender can safely transmit a new packet without increasing congestion as well as it can increase its send window slowly to probe for equilibrium. By using ACKs to pace the transmission of packets, TCP is said to be self-clocking. A timeout signal or other methods of loss detection implies that the network might be congested and thus the sender should reduce its sending rate. ECN (Explicit Congestion Notification) is an explicit mechanism that provides feedback from the network about congestion."```

**Comment by goelvidhi** [comment]
Basically - remove TCP as this is applicable to any sender and other text changes

**Comment by drbruced12** [comment]
The issue here is that we're trying to help the reader understand how TCP congestion control was developed as a series of incremental steps starting in 1988. Not until relatively late in the process (e.g. with the rise of TFRC, DCCP, and much later, QUIC) did the ideas of TCP congestion control make it into other protocols. This is, after all, a book on TCP Congestion Control. We do have a chapter ("Beyond TCP") that makes your point - these ideas don't have to be part of TCP. But to try to tell the story as if congestion control is independent of TCP misses the historical context which we were involved with and which we want the reader to understand.
